### ISSUE TITLE
No 'results.csv' file or directory

### ISSUE THREAD

**Issue by sobertie** [LinaDongXMU/GXLE#9]
Whenever I run the GXLE.sh file, the following errors encounter -
mkdir: cannot create directory ‘xscore’: File exists
mkdir: cannot create directory ‘ligand’: File exists
GXLE.sh: line 4: bjobs: command not found
run_min2.sh: line 2: /home/mohon/.cshrc: No such file or directory
GXLE.sh: line 4: bjobs: command not found
run_gbsa.sh: line 3: /home/mohon/.cshrc: No such file or directory
ls: cannot access '*_FINAL_RESULTS_MMPBSA.dat': No such file or directory
hdac
xscore.sh: line 9: xscore: command not found
grep: xscore.log: No such file or directory
Traceback (most recent call last):
  File "/home/mohon/GXLE/application/for_model/GXLE.py", line 12, in <module>
    x_test=transfer.fit_transform(x_test)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohon/anaconda3/envs/gxle/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohon/anaconda3/envs/gxle/lib/python3.12/site-packages/sklearn/base.py", line 916, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohon/anaconda3/envs/gxle/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 839, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohon/anaconda3/envs/gxle/lib/python3.12/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohon/anaconda3/envs/gxle/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 875, in partial_fit
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/mohon/anaconda3/envs/gxle/lib/python3.12/site-packages/sklearn/base.py", line 605, in _validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohon/anaconda3/envs/gxle/lib/python3.12/site-packages/sklearn/utils/validation.py", line 967, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 22)) while a minimum of 1 is required by StandardScaler.
cp: cannot stat 'results.csv': No such file or directory

Please help me with this issue.

**Comment by LinaDongXMU** [comment]
See https://github.com/LinaDongXMU/GXLE/tree/main/Default-AmberEnv to default the error of “bjobs”. About other errors you can see requirements.txt in detail at first.
